Bug 1745031 - [PULSEBOT] Add improved logging support in the format of MozLog
mozilla-conduit/pulsebot-old pull request #1
Opened 2021-12-08 18:45 UTC by dklawren

2021-12-08 20:44 UTC, mitchhentges approved these changes
Very tentative approval, because I don't want to block you out here in this other project.
Due to my lack of familiarity, I'd personally prefer that you hold on until Zeid's review before landing this.

Thanks for docker-ifying this project, this is great!

2021-12-08 20:44 UTC, mitchhentges commented on pulsebot/logging.py
> +    https://mzl.la/2NhT1E6
Woah, did you go GPS-mode and slam out all of this logging code, or did you re-use this from somewhere else? There's a lot, and it seems pretty serious 😳 

-----

Another option is to re-use the formatter implementation [defined in `python-dockerflow`](https://python-dockerflow.readthedocs.io/en/main/api/logging.html#dockerflow.logging.JsonLogFormatter), which is [deployed to PyPi here](https://pypi.org/project/dockerflow/).
(Setup docs are [here](https://python-dockerflow.readthedocs.io/en/main/logging.html)).

What do you think?

2021-12-08 20:44 UTC, mitchhentges commented on pulsebot/bugzilla.py
> +            logger.warn(f"BugzillaError: {args[0]}")
Nit: I'd recommend that your exception handler do the logging/warning of errors.
Otherwise, cases the like the following will unexpectedly log `BugzillaError`:
```
try:
    fn_that_raises_error()
except BugzillaError:
    pass # We can ignore the error because [it's expected/this is a test/some other reason/magic]
```

This change will also align `BugzillaError`'s behaviour with Pythonic exceptions, which all exist to _carry_ exception information, but not affect external state.

2021-12-08 20:44 UTC, mitchhentges commented on pulsebot/bugzilla.py
> +            ",".join(fields),
This feels like it might be a fix that belongs in a separate patch/commit? I dont' follow how this is needed for logging

2021-12-08 20:44 UTC, mitchhentges commented on pulsebot/pulse_dispatch.py
> +            )
These formatting changes should ideally be in another patch/PR IMO

2021-12-08 21:16 UTC, zzzeid requested changes
Minor changes requested, otherwise lgtm!

2021-12-08 21:16 UTC, zzzeid commented on pulsebot/bugzilla.py
> +            logger.warn(f"BugzillaError: {args[0]}")
I would second this (i.e. I recommend logging this error where the exception occurs).

Additionally, the log level should be `ERROR`, i.e. use `logger.exception` or `logger.error` and not `logger.warning`, since this exception is raised after catching other exceptions.

2021-12-08 21:16 UTC, zzzeid commented on pulsebot/bugzilla.py
> +        logger.info(f"get_fields: {bug_url}")
This logger may benefit from additional formatting parameters in the formatter configuration, e.g. `funcName` and/or `module` so you don't have to manually put this in the actual log call (in this example and others in the PR).

See https://docs.python.org/3/library/logging.html#logrecord-attributes for more info.

2021-12-08 21:16 UTC, zzzeid commented on pulsebot/bugzilla.py
> +            raise BugzillaError(f"Error occurred posting comment to {post_url}")
Should keep track of actual exception (i.e. `except Exception as e`) above and expose some of that info in the `BugzillaError` instance here. Same thing for line 91.

2021-12-08 21:16 UTC, zzzeid commented on pulsebot/logging.py
> +    https://mzl.la/2NhT1E6
If using dockerflow mentioned by @mitchhentges above is an option -- that would be superior to putting this file here (looks like you can [import the formatter directly](https://python-dockerflow.readthedocs.io/en/main/api/logging.html#dockerflow.logging.JsonLogFormatter)). But it might also be good to get some cloudops eyes on this, in case they have a different idea of what's ideal for new implementations.

2021-12-08 21:19 UTC, dklawren commented on pulsebot/bugzilla.py
> +            ",".join(fields),
Ah yeah. I noticed the old code was using '+' instead of ',' which technically both work in the BMO REST API but I prefer ','.

2021-12-08 21:21 UTC, dklawren commented on pulsebot/pulse_dispatch.py
> +            )
Sorry bout that. I will be a little less happy with the format document feature for future PRs. If it is an issue I will update this PR to remove the formatting changes.

2021-12-08 23:08 UTC, dklawren commented
Please let me know if the BugzillaError exception changes are in line with what you both were describing or if I am still off. Thanks!

2021-12-08 23:43 UTC, mitchhentges approved these changes
LGTM 👍

2021-12-08 23:43 UTC, mitchhentges commented on logging.ini
> + class = dockerflow.logging.JsonLogFormatter
Nit: chuck a newline at the end of this file

2021-12-15 15:00 UTC, zzzeid requested changes
Small requests otherwise looks good.

2021-12-15 15:00 UTC, zzzeid commented on pulsebot/bugzilla.py
> +            logger.exception(
Technically there is no exception prior to this log entry here, so this should be `logger.error`. 
```suggestion
            logger.error(
```

2021-12-15 15:00 UTC, zzzeid commented on pulsebot/bugzilla.py
> +            logger.exception(
```suggestion
            logger.error(
```

2021-12-15 15:00 UTC, zzzeid commented on pulsebot/pulse_hgpushes.py
> +            logger.exception(f"Failure getting {push_url} {r.status_code}")
```suggestion
            logger.error(f"Failure getting {push_url} {r.status_code}")
```

Would be good to add a `logger.info` here saying that we are trying again.

2021-12-15 21:07 UTC, merged